#!/usr/bin/env bash

# Prepare yay pacman wrapper (in $HOME)
cd $HOME
which yay || git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
cd $HOME
rm -rf yay

xargs -p -a pkglist.txt yay --noredownload --norebuild --clean -S

# enable and start necessary services (for systray and startup)
sudo systemctl enable NetworkManager.service && systemctl start NetworkManager.service
sudo systemctl enable bluetooth.service && systemctl start bluetooth.service
sudo systemctl enable sshd.service && systemctl start sshd.service

# Tools are obtained if missing:
# SpaceVim
[ -d "$HOME/.SpaceVim" ] || curl -sLf https://spacevim.org/install.sh | bash

# Sdkman
which sdk || curl -s "https://get.sdkman.io" | bash

# Pip packages
pip install --user tmuxp
